_veh = vehicle

if (_veh in [
			
"pop_camion_antidisturbios1",
"c4_aircross_cnp",
"c4_picasso_08_cnp",
"c4_picasso_16_cnp",
"pop_citroen_c4_picasso_2016_cnp1",
"pop_citroen_xsara_picasso_cnp1",
"pop_citroen_xsara_picasso_cnp2",
"ford_kuga_cnp",
"pop_cherokee_CNP1",
"pop_mercedes_sprinter_corta_policia1",
"pop_mercedes_benz_vito_cnp1",
"pop_nissan_pathfinder_cnp1",
"pop_nissan_patrol_cnp1",
"nissan_qashqai_2016_cnp",
"nissan_qashqai_cnp",
"nissan_terrano_ii_cnp",
"nissan_terrano_ii_cnp2",
"nissan_xtrail_2015_cnp",
"nissan_xtrail_cnp",
"pop_opel_vivaro_cnp1",
"peugeot_expert_cnp",
"altea_xl_cnp",
"toyota_prius_cnp",
"pop_yamaha_xt660r_cnp_atgc",
"pop_autocar_presos",
"pop_citroen_c4_gc1",
"pop_citroen_c4_picasso_2016_gc1",
"pop_citroen_c4_picasso_gc1",
"pop_fiat_bravo_gc1",
"ford_kuga_gc",
"pop_honda_crv_gc1",
"pop_land_rover_freelander_gc1",
"pop_mercedes_sprinter_corta_policia2",
"pop_mitsubishi_asx_gc1",
"pop_mitsubishi_montero_gc1",
"pop_nissan_leaf_p",
"nissan_pathfinder_gc",
"pop_nissan_patrol_gc1",
"nissan_primastar_gc",
"pop_nissan_qashqai_2016_policia1",
"nissan_terrano_ii_gc",
"nissan_xtrail_2015_gc",
"pop_nissan_xtrail_policia1",
"opel_astra_j_gc",
"pop_opel_astra_h_gc1",
"pop_opel_astra_j_gc1",
"peugeot_308_gc",
"pop_peugeot_406_gc1",
"pop_megane",
"toyota_prado_gc",
"alfa_romeo_159",
"bmw_1200_rt",
"citroen_c5",
"ford_modeo_2016",
"ford_modeo_2016_v2",
"ford_mondeo",
"jeep_grand_cherokee",
"pop_mercedes_sprinter_corta_atgc1",
"mercedes_benz_vito",
"mercedes_sprinter_corta_2",
"pop_mitsubishi_asx_atgc",
"mitsubishi_montero_2",
"nissan_pathfinder_atgc",
"pop_nissan_qashqai_atgc1",
"nissan_xtrail_atgc",
"opel_insignia",
"peugeot_407",
"peugeot_expert",
"renault_trafic",
"toyota_camry",
"toyota_prado_atgc",
"nissan_qashqai_cnp_front",
"nissan_pathfinder_gc_frontera",
"nissan_primastar_gc_frontera",
"peugeot_expert_cnp_frontera",
"pop_nissan_pathfinder_uip1",
"pop_nissan_pathfinder_gar",
"pop_toyota_prado_gar",
"pop_vamtac_cnp"]) exitWith {
        while {true} do {
        hint "No puedes pilotar vehiculos que no son de tu facción";
		moveout player;
		nopilotacoche = true;
		sleep 1;
    };
};